FROM ubuntu:20.04
COPY . .
RUN apt-get update
#RUN /../Setup.sh
RUN apt-get upgrade -y
RUN apt-get install apt-utils net-tools systemctl sudo -y
RUN apt-get install python3 python3-pip ncat git iputils-ping mysql-server mysql-client -y
RUN pip3 install django mysql-connector-python
#RUN mysql_secure_installation
#RUN mysqld --initialize