FROM ubuntu:20.04
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install apt-utils net-tools systemctl sudo -y
RUN apt-get install python3 wget unzip python3-pip ncat git iputils-ping mysql-server mysql-client -y
RUN pip3 install django mysql-connector-python
#When using Docker please add the a Username and Password
#RUN echo Unless You Have Edited the files, the Username and password is toor
RUN wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
RUN unzip ngrok-stable-linux-amd64.zip -d /bin/
COPY . .